#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    #line 1 "..\..\Modules\Common\Views\Account\Login.cshtml"
    using Version = Easy.Web.CMS.Version;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Account/Login.cshtml")]
    public partial class _Modules_Common_Views_Account_Login_cshtml : Easy.Web.Page.ViewPage<dynamic>
    {
        public _Modules_Common_Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Modules\Common\Views\Account\Login.cshtml"
  
    ViewBag.Title = Version.CurrentVersion;
    Style.Reqiured("admin").AtHead();
    Style.Reqiured("Login").AtHead();
    Script.Reqiured("validate").AtFoot();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Modules\Common\Views\Account\Login.cshtml"
 using (Html.BeginForm())
{


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"login-panel\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"login-panel-heading\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"http://www.zkea.net/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" class=\"logo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 414), Tuple.Create("\"", 450)
, Tuple.Create(Tuple.Create("", 420), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Images/logo_zkea.png")
, 420), false)
);

WriteLiteral(" alt=\"ZKEACMS\"");

WriteLiteral(" />\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"login-panel-body\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" class=\"version text-center\"");

WriteLiteral(">");

            
            #line 19 "..\..\Modules\Common\Views\Account\Login.cshtml"
                                       Write(Version.CurrentVersion);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n            <p>请输入您的用户信息以登录系统</p>\r\n            <div");

WriteLiteral(" class=\"form-input\"");

WriteLiteral(">\r\n                <h4>用户名</h4>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"userName\"");

WriteLiteral(" name=\"userName\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"请输入用户名\"");

WriteLiteral("/>\r\n                <span");

WriteLiteral(" class=\"field-validation-valid \"");

WriteLiteral(" data-valmsg-for=\"userName\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-input\"");

WriteLiteral(">\r\n                <h4>密码</h4>\r\n                <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"password\"");

WriteLiteral(" name=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"请输入密码\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"field-validation-valid\"");

WriteLiteral(" data-valmsg-for=\"password\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral("></span>\r\n            </div>\r\n");

            
            #line 31 "..\..\Modules\Common\Views\Account\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Modules\Common\Views\Account\Login.cshtml"
             if (ViewBag.Errormessage != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"text-center alert alert-danger\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 34 "..\..\Modules\Common\Views\Account\Login.cshtml"
               Write(ViewBag.Errormessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 36 "..\..\Modules\Common\Views\Account\Login.cshtml"
            }            

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger btn-login\"");

WriteLiteral(" value=\"登录\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"login-panel-footer\"");

WriteLiteral(">\r\n            <p>\r\n                <a");

WriteLiteral(" href=\"http://www.zkea.net/licenses\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">许可协议</a>\r\n            </p>\r\n            <p>\r\n                Copyright © 2015-");

            
            #line 46 "..\..\Modules\Common\Views\Account\Login.cshtml"
                            Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" ZKEASOFT. All Rights Reserved | <a");

WriteLiteral(" href=\"http://www.zkea.net\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">www.zkea.net</a>\r\n            </p>\r\n        </div>\r\n    </div>\r\n");

            
            #line 50 "..\..\Modules\Common\Views\Account\Login.cshtml"
}

            
            #line default
            #line hidden
            
            #line 51 "..\..\Modules\Common\Views\Account\Login.cshtml"
 using (Script.AtFoot())
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" async");

WriteLiteral(" src=\"http://www.zkea.net/openstatistics\"");

WriteLiteral("></script>\r\n");

            
            #line 54 "..\..\Modules\Common\Views\Account\Login.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
