#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Error/Forbidden.cshtml")]
    public partial class _Modules_Common_Views_Error_Forbidden_cshtml : Easy.Web.Page.ViewPage<dynamic>
    {
        public _Modules_Common_Views_Error_Forbidden_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Modules\Common\Views\Error\Forbidden.cshtml"
  
    ViewBag.Title = "没有权限";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n    <br /><br />\r\n    <h1");

WriteLiteral(" style=\"font-size: 4em\"");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">请求被拒绝</h1>\r\n</div>\r\n<div");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n    <h2>您没有足够的权限</h2>\r\n    <br />\r\n    <br />\r\n    <p>在处理您的请求时出现错误，因为您没有相关的权限，" +
"请与管理员联系。</p>\r\n    <br />\r\n    <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">或者您还可以访问其它页面：</p>\r\n    <br />\r\n    <p>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 393), Tuple.Create("\"", 402)
, Tuple.Create(Tuple.Create("", 400), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 400), false)
);

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">访问首页</a>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 445), Tuple.Create("\"", 482)
            
            #line 18 "..\..\Modules\Common\Views\Error\Forbidden.cshtml"
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(Url.Action("Login","Account")
            
            #line default
            #line hidden
, 452), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">重新登录</a>\r\n        <a");

WriteLiteral(" href=\"http://www.zkea.net/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">ZKEASOFT</a>\r\n        <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">ZKEACMS</a>\r\n    </p>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
