#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Error/Index.cshtml")]
    public partial class _Modules_Common_Views_Error_Index_cshtml : Easy.Web.Page.ViewPage<dynamic>
    {
        public _Modules_Common_Views_Error_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Modules\Common\Views\Error\Index.cshtml"
  
    ViewBag.Title = "服务器错误";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n    <br /><br />\r\n    <h1");

WriteLiteral(" style=\"font-size: 6em\"");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">500</h1>\r\n</div>\r\n<div");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n    <h2>服务器错误</h2>\r\n    <br />\r\n    <br />\r\n    <p>服务器在响应您的请求时出错，您可以重新检查一下访问的U" +
"RL地址是否正确，或者联系管理员。</p>\r\n    <br />\r\n    <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">或者您还可以访问其它页面：</p>\r\n    <br />\r\n    <p>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 401), Tuple.Create("\"", 410)
, Tuple.Create(Tuple.Create("", 408), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 408), false)
);

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">访问首页</a>\r\n        <a");

WriteLiteral(" href=\"http://www.zkea.net/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">ZKEASOFT</a>\r\n        <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">ZKEACMS</a>\r\n    </p>\r\n</div>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
