#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    
    #line 1 "..\..\Views\Shared\_AdminLayout.cshtml"
    using Easy.Web.CMS;
    
    #line default
    #line hidden
    using Easy.Web.Extend;
    
    #line 2 "..\..\Views\Shared\_AdminLayout.cshtml"
    using Microsoft.Practices.ServiceLocation;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_AdminLayout.cshtml"
    using MvcSiteMapProvider.Web.Html;
    
    #line default
    #line hidden
    using MvcSiteMapProvider.Web.Html.Models;
    
    #line 4 "..\..\Views\Shared\_AdminLayout.cshtml"
    using Version = Easy.Web.CMS.Version;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_AdminLayout.cshtml")]
    public partial class _Views_Shared__AdminLayout_cshtml : Easy.Web.Page.ViewPage<dynamic>
    {
        public _Views_Shared__AdminLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_AdminLayout.cshtml"
  
    Style.Reqiured("bootStrap").AtHead();
    Style.Reqiured("admin").AtHead();
    Script.Reqiured("admin").AtFoot();
    var plugs = ServiceLocator.Current.GetAllInstances<PluginBase>();
    List<AdminMenu> menus = new List<AdminMenu>();
    plugs.Each(m =>
    {
        var menu = m.AdminMenu();
        if (menu != null)
        {
            var adminMenus = menu as AdminMenu[] ?? menu.ToArray();
            menus.AddRange(adminMenus);
        }
    });
    if (ApplicationContext.CurrentUser == null)
    {
        FormsAuthentication.SignOut();
        Response.Redirect("~/");
        return;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>ZKEASOFT</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 963), Tuple.Create("\"", 983)
, Tuple.Create(Tuple.Create("", 970), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 970), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 35 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(StyleAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(ScriptAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n\r\n    <div");

WriteLiteral(" id=\"wrap\"");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n        <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"http://www.zkea.net\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" title=\"ZKEASOFT\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1477), Tuple.Create("\"", 1530)
, Tuple.Create(Tuple.Create("", 1483), Tuple.Create<System.Object, System.Int32>(Href("~/Content/themes/Admin/images/logo_zkea_min.png")
, 1483), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" style=\"height: 20px;\"");

WriteLiteral(" />\r\n                    </a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"navbar-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\Shared\_AdminLayout.cshtml"
                   Write(Version.CurrentVersion);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1900), Tuple.Create("\"", 1909)
, Tuple.Create(Tuple.Create("", 1907), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1907), false)
);

WriteLiteral(">查看站点</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/videos\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">演示视频</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/templates\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">下载模板</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/theme\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">下载主题</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/extend\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">扩展插件</a>\r\n                        </li>\r\n                        <li>\r\n         " +
"                   <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/document\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">文档</a>\r\n                        </li>\r\n                    </ul>\r\n              " +
"      <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/price\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-copyright-mark\"");

WriteLiteral("></i>\r\n                                商业授权\r\n                            </a>\r\n  " +
"                      </li>\r\n                        <li>\r\n                     " +
"       <a");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/donate\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-usd\"");

WriteLiteral("></i>\r\n                                赞助\r\n                            </a>\r\n    " +
"                    </li>\r\n                        <li>\r\n                       " +
"     <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3505), Tuple.Create("\"", 3544)
            
            #line 86 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3512), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Account")
            
            #line default
            #line hidden
, 3512), false)
);

WriteLiteral(" target=\"_self\"");

WriteLiteral(" title=\"退出\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-off\"");

WriteLiteral("></i>\r\n                                退出\r\n                            </a>\r\n    " +
"                    </li>\r\n                    </ul>\r\n                </div>\r\n\r\n" +
"            </div>\r\n        </nav>\r\n        <nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-left\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"userInfo\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4045), Tuple.Create("\"", 4108)
            
            #line 100 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4051), Tuple.Create<System.Object, System.Int32>(Url.PathContent(ApplicationContext.CurrentUser.PhotoUrl)
            
            #line default
            #line hidden
, 4051), false)
);

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" />\r\n                        <strong>");

            
            #line 101 "..\..\Views\Shared\_AdminLayout.cshtml"
                           Write(ApplicationContext.CurrentUser.UserName);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n                    </div>\r\n                </div>\r\n                <u" +
"l");

WriteLiteral(" id=\"main-menu\"");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n");

            
            #line 105 "..\..\Views\Shared\_AdminLayout.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\_AdminLayout.cshtml"
                     foreach (AdminMenu menu in menus.Where(m => Authorizer.Authorize(m.PermissionKey)).OrderBy(m => m.Order))
                    {
                        if (menu.Children != null && menu.Children.Any())
                        {
                            if (menu.Children.Any(m => Authorizer.Authorize(m.PermissionKey)))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <li");

WriteLiteral(" class=\"accordion-group\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"b_9FDDF6 group-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <i");

WriteAttribute("class", Tuple.Create(" class=\"", 4890), Tuple.Create("\"", 4918)
, Tuple.Create(Tuple.Create("", 4898), Tuple.Create("glyphicon", 4898), true)
            
            #line 113 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create(" ", 4907), Tuple.Create<System.Object, System.Int32>(menu.Icon
            
            #line default
            #line hidden
, 4908), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                                        ");

            
            #line 114 "..\..\Views\Shared\_AdminLayout.cshtml"
                                   Write(menu.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <i");

WriteLiteral(" class=\"glyphicon group\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"    <div");

WriteLiteral(" class=\"accordion-inner\"");

WriteLiteral(">\r\n");

            
            #line 118 "..\..\Views\Shared\_AdminLayout.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\Shared\_AdminLayout.cshtml"
                                         foreach (AdminMenu child in menu.Children.Where(m => Authorizer.Authorize(m.PermissionKey)).OrderBy(m => m.Order))
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <a");

WriteAttribute("id", Tuple.Create(" id=\"", 5407), Tuple.Create("\"", 5459)
, Tuple.Create(Tuple.Create("", 5412), Tuple.Create("menu", 5412), true)
            
            #line 120 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create("", 5416), Tuple.Create<System.Object, System.Int32>((child.Url ?? child.Title).GetHashCode()
            
            #line default
            #line hidden
, 5416), false)
);

WriteLiteral(" class=\"b_9FDDF6 menu-item\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5487), Tuple.Create("\"", 5525)
            
            #line 120 "..\..\Views\Shared\_AdminLayout.cshtml"
                                                     , Tuple.Create(Tuple.Create("", 5494), Tuple.Create<System.Object, System.Int32>(Url.Content(child.Url ?? "~/")
            
            #line default
            #line hidden
, 5494), false)
);

WriteLiteral(">\r\n                                                <i");

WriteAttribute("class", Tuple.Create(" class=\"", 5579), Tuple.Create("\"", 5608)
, Tuple.Create(Tuple.Create("", 5587), Tuple.Create("glyphicon", 5587), true)
            
            #line 121 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create(" ", 5596), Tuple.Create<System.Object, System.Int32>(child.Icon
            
            #line default
            #line hidden
, 5597), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                                                ");

            
            #line 122 "..\..\Views\Shared\_AdminLayout.cshtml"
                                           Write(child.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </a>\r\n");

            
            #line 124 "..\..\Views\Shared\_AdminLayout.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </li>" +
"\r\n");

            
            #line 127 "..\..\Views\Shared\_AdminLayout.cshtml"
                            }
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteAttribute("id", Tuple.Create(" id=\"", 6037), Tuple.Create("\"", 6087)
, Tuple.Create(Tuple.Create("", 6042), Tuple.Create("menu", 6042), true)
            
            #line 132 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6046), Tuple.Create<System.Object, System.Int32>((menu.Url ?? menu.Title).GetHashCode()
            
            #line default
            #line hidden
, 6046), false)
);

WriteLiteral(" class=\"b_9FDDF6 menu-item\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6115), Tuple.Create("\"", 6152)
            
            #line 132 "..\..\Views\Shared\_AdminLayout.cshtml"
                                       , Tuple.Create(Tuple.Create("", 6122), Tuple.Create<System.Object, System.Int32>(Url.Content(menu.Url ?? "~/")
            
            #line default
            #line hidden
, 6122), false)
);

WriteLiteral(">\r\n                                    <i");

WriteAttribute("class", Tuple.Create(" class=\"", 6194), Tuple.Create("\"", 6222)
, Tuple.Create(Tuple.Create("", 6202), Tuple.Create("glyphicon", 6202), true)
            
            #line 133 "..\..\Views\Shared\_AdminLayout.cshtml"
, Tuple.Create(Tuple.Create(" ", 6211), Tuple.Create<System.Object, System.Int32>(menu.Icon
            
            #line default
            #line hidden
, 6212), false)
);

WriteLiteral("></i>\r\n");

WriteLiteral("                                    ");

            
            #line 134 "..\..\Views\Shared\_AdminLayout.cshtml"
                               Write(menu.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");

            
            #line 137 "..\..\Views\Shared\_AdminLayout.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n            </div>\r\n\r\n        </nav>\r\n        <div");

WriteLiteral(" class=\"main-container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"site-map\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 145 "..\..\Views\Shared\_AdminLayout.cshtml"
           Write(Html.MvcSiteMap().SiteMapPath());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"main-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 148 "..\..\Views\Shared\_AdminLayout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 152 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(StyleAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 153 "..\..\Views\Shared\_AdminLayout.cshtml"
Write(ScriptAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" async");

WriteLiteral(" src=\"http://www.zkea.net/openstatistics\"");

WriteLiteral("></script>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
