SET IDENTITY_INSERT [dbo].[SectionGroup] ON 

INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (1, N'组1', N'80f365c7991a49a0b04aa11006018814', N'SectionTemplate.Default', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (2, N'组1', N'604b2461f7c545e28dbb21fb15def5c7', N'SectionTemplate.Default', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (3, N'组1', N'8aa84a350d4242be889dcbec18e24b2a', N'SectionTemplate.Default', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (4, N'组1', N'223a591f9d434539a2bae9e6de7bc3cf', N'SectionTemplate.Default', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (5, N'G1', N'2b3eb61307d24c50a6b3aaa75db3810e', N'SectionTemplate.ListView', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (6, N'G1', N'00f62c5acfe840e0bee3ca2979f0f025', N'SectionTemplate.ImageRight', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (7, N'G1', N'f6f11ba2fec844de883acf0a1fe3eb89', N'SectionTemplate.ImageRight', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (8, N'G1', N'481574ebc98b4cdf9a07e3f20c1ab78d', N'SectionTemplate.ListView', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (9, N'左', N'b568ff7f4a894870adaf9afadf787bf9', N'SectionTemplate.Default', 1, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-6')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (10, N'右', N'b568ff7f4a894870adaf9afadf787bf9', N'SectionTemplate.Default', 2, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-6')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (11, N'左', N'55b73e54fd054de4847960bdac350c6d', N'SectionTemplate.Default', 1, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-6')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (12, N'右', N'55b73e54fd054de4847960bdac350c6d', N'SectionTemplate.Default', 2, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-6')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (13, N'左', N'ed837392097f4e60b812bc57111dd762', N'SectionTemplate.Default', 1, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (14, N'中', N'ed837392097f4e60b812bc57111dd762', N'SectionTemplate.Default', 2, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (15, N'右', N'ed837392097f4e60b812bc57111dd762', N'SectionTemplate.Default', 3, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (16, N'左', N'1fb967867e3b440e86336bc5a51e8719', N'SectionTemplate.Default', 1, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (17, N'中', N'1fb967867e3b440e86336bc5a51e8719', N'SectionTemplate.Default', 2, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
INSERT [dbo].[SectionGroup] ([ID], [GroupName], [SectionWidgetId], [PartialView], [Order], [CreateBy], [CreatebyName], [CreateDate], [LastUpdateBy], [LastUpdateByName], [LastUpdateDate], [PercentWidth]) VALUES (18, N'右', N'1fb967867e3b440e86336bc5a51e8719', N'SectionTemplate.Default', 3, NULL, NULL, NULL, NULL, NULL, NULL, N'col-sm-4')
SET IDENTITY_INSERT [dbo].[SectionGroup] OFF
GO
