#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Shared/_DesignPageLayout.cshtml")]
    public partial class _Modules_Common_Views_Shared__DesignPageLayout_cshtml : Easy.Web.Page.ViewPage<Easy.Web.CMS.Layout.LayoutEntity>
    {
        public _Modules_Common_Views_Shared__DesignPageLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
  
    if (Model == null)
    {
        return;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html");

WriteLiteral(" class=\"ie ie6\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 7 ]><html");

WriteLiteral(" class=\"ie ie7\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 8 ]><html");

WriteLiteral(" class=\"ie ie8\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<html");

WriteLiteral(" class=\"not-ie\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"cache-control\"");

WriteLiteral(" content=\"no-store\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"expires\"");

WriteLiteral(" content=\"-1\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"pragma\"");

WriteLiteral(" content=\"no-cache\"");

WriteLiteral(" />\r\n\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>[设计]");

            
            #line 25 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
          Write(Model.Page.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 898), Tuple.Create("\"", 918)
, Tuple.Create(Tuple.Create("", 905), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 905), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 28 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
Write(StyleAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 29 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
Write(ScriptAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 30 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
     if (Model.CurrentTheme != null)
    {
        if (HttpContext.Current.IsDebuggingEnabled)
        {

            
            #line default
            #line hidden
WriteLiteral("            <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1223), Tuple.Create("\"", 1274)
            
            #line 34 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1230), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.CurrentTheme.UrlDebugger)
            
            #line default
            #line hidden
, 1230), false)
);

WriteLiteral(" />\r\n");

            
            #line 35 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1366), Tuple.Create("\"", 1409)
            
            #line 38 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 1373), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.CurrentTheme.Url)
            
            #line default
            #line hidden
, 1373), false)
);

WriteLiteral(" />\r\n");

            
            #line 39 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</head>\r\n<body");

WriteLiteral(" class=\"front\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" id=\"toolBar\"");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle collapsed\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    </button>\r\n                    <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral("><span");

WriteLiteral(" class=\"badge\"");

WriteLiteral(">页面设计</span></a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a>\r\n               " +
"                 <label");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"helper\"");

WriteLiteral(" data-class=\"design-border\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(@" checked />
                                    <span>
                                        边框(显示空区域)
                                    </span>
                                </label>
                            </a>
                        </li>
                        <li>
                            <a>
                                <label");

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" class=\"helper\"");

WriteLiteral(" data-class=\"hideToolBar\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" autocomplete=\"off\"");

WriteLiteral(@" checked />
                                    <span>
                                        工具栏
                                    </span>
                                </label>
                            </a>
                        </li>
                    </ul>
                    <div");

WriteLiteral(" class=\"navbar-form navbar-right\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3520), Tuple.Create("\"", 3601)
            
            #line 80 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3527), Tuple.Create<System.Object, System.Int32>(Url.Action("RedirectView", "Page", new {module = "admin", Model.Page.ID})
            
            #line default
            #line hidden
, 3527), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></i>\r\n                                预览\r\n                            </a>\r\n    " +
"                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3805), Tuple.Create("\"", 3888)
            
            #line 84 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 3812), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Page", new {module = "admin", PageID = Model.Page.ID})
            
            #line default
            #line hidden
, 3812), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-th\"");

WriteLiteral("></i>\r\n                                概览\r\n                            </a>\r\n    " +
"                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4088), Tuple.Create("\"", 4184)
            
            #line 88 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4095), Tuple.Create<System.Object, System.Int32>(Url.Action("Design", "Layout", new {module = "admin", Model.ID, PageID = Model.Page.ID})
            
            #line default
            #line hidden
, 4095), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-th-list\"");

WriteLiteral("></i>\r\n                                布局\r\n                            </a>\r\n    " +
"                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4389), Tuple.Create("\"", 4462)
            
            #line 92 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4396), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "Page", new {module = "admin", Model.Page.ID})
            
            #line default
            #line hidden
, 4396), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral("></i>\r\n                                属性\r\n                            </a>\r\n    " +
"                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4664), Tuple.Create("\"", 4772)
            
            #line 96 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4671), Tuple.Create<System.Object, System.Int32>(Url.Action("PublishPage", "Page", new {module = "admin", Model.Page.ID, ReturnUrl = Model.Page.Url})
            
            #line default
            #line hidden
, 4671), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-open\"");

WriteLiteral("></i>\r\n                                发布\r\n                            </a>\r\n    " +
"                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4974), Tuple.Create("\"", 5074)
            
            #line 100 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 4981), Tuple.Create<System.Object, System.Int32>(Url.Action("SelectWidget", "WidgetTemplate", new {module = "admin", pageId = Model.Page.ID})
            
            #line default
            #line hidden
, 4981), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i>\r\n                                添加内容\r\n                            </a>\r\n  " +
"                          <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" class=\"upload-template btn btn-primary\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"glyphicon glyphicon-copy\"");

WriteLiteral("></i>\r\n                                安装模板\r\n                            </a>\r\n\r\n" +
"");

            
            #line 109 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 109 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
                             if (Model.CurrentTheme != null && Model.CurrentTheme.IsPreView)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5654), Tuple.Create("\"", 5722)
            
            #line 111 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 5661), Tuple.Create<System.Object, System.Int32>(Url.Action("CancelPreView", "Theme", new {module = "admin"})
            
            #line default
            #line hidden
, 5661), false)
);

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"glyphicon glyphicon-transfer\"");

WriteLiteral("></i>\r\n                                    退出\r\n");

WriteLiteral("                                    ");

            
            #line 114 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
                               Write(Model.CurrentTheme.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    主题\r\n                                </a>\r\n");

            
            #line 117 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 118 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
                       Write(Html.Partial("Partial.Menu", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n\r\n                    </div>\r\n                <" +
"/div>\r\n            </div>\r\n\r\n            <form");

WriteLiteral(" id=\"template-form\"");

WriteAttribute("action", Tuple.Create(" action=\"", 6230), Tuple.Create("\"", 6309)
            
            #line 125 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6239), Tuple.Create<System.Object, System.Int32>(Url.Action("InstallWidgetTemplate", "Widget", new {module = "admin"})
            
            #line default
            #line hidden
, 6239), false)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"returnUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6410), Tuple.Create("\"", 6443)
            
            #line 126 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6418), Tuple.Create<System.Object, System.Int32>(Request.Url.PathAndQuery
            
            #line default
            #line hidden
, 6418), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" id=\"template-file\"");

WriteLiteral(" name=\"template\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"hidden\"");

WriteLiteral(" />\r\n            </form>\r\n        </div>\r\n    </nav>\r\n    <div");

WriteLiteral(" id=\"containers\"");

WriteLiteral(" class=\"pagePreview design-border\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 132 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 135 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
Write(StyleAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 136 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
Write(ScriptAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 137 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 137 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
     if (!Model.Style.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 6786), Tuple.Create("\"", 6818)
            
            #line 139 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6793), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Style)
            
            #line default
            #line hidden
, 6793), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 140 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 141 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
     if (!Model.Page.Style.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 6913), Tuple.Create("\"", 6950)
            
            #line 143 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 6920), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Page.Style)
            
            #line default
            #line hidden
, 6920), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 144 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 145 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
     if (!Model.Script.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7066), Tuple.Create("\"", 7098)
            
            #line 147 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 7072), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Script)
            
            #line default
            #line hidden
, 7072), false)
);

WriteLiteral("></script>\r\n");

            
            #line 148 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 149 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
     if (!Model.Page.Script.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7209), Tuple.Create("\"", 7246)
            
            #line 151 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
, Tuple.Create(Tuple.Create("", 7215), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Page.Script)
            
            #line default
            #line hidden
, 7215), false)
);

WriteLiteral("></script>\r\n");

            
            #line 152 "..\..\Modules\Common\Views\Shared\_DesignPageLayout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
