#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    #line 1 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    using Version = Easy.Web.CMS.Version;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Shared/_Layout.cshtml")]
    public partial class _Modules_Common_Views_Shared__Layout_cshtml : Easy.Web.Page.ViewPage<Easy.Web.CMS.Layout.LayoutEntity>
    {
        public _Modules_Common_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
  
    if (Model == null)
    {
        return;
    }
    Style.Reqiured("Easy").AtFoot();

            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- http://www.zkea.net/ Copyright 2016 ZKEASOFT http://www.zkea.net/licenses " +
"-->\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html");

WriteLiteral(" class=\"ie ie6\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 7 ]><html");

WriteLiteral(" class=\"ie ie7\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 8 ]><html");

WriteLiteral(" class=\"ie ie8\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<html");

WriteLiteral(" class=\"not-ie\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <title>");

            
            #line 22 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
      Write(Model.Page.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteAttribute("content", Tuple.Create(" content=\"", 796), Tuple.Create("\"", 831)
            
            #line 23 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 806), Tuple.Create<System.Object, System.Int32>(Model.Page.MetaKeyWorlds
            
            #line default
            #line hidden
, 806), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteAttribute("content", Tuple.Create(" content=\"", 865), Tuple.Create("\"", 902)
            
            #line 24 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 875), Tuple.Create<System.Object, System.Int32>(Model.Page.MetaDescription
            
            #line default
            #line hidden
, 875), false)
);

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"ZKEASOFT\"");

WriteLiteral("/>\r\n    <meta");

WriteLiteral(" name=\"about\"");

WriteAttribute("content", Tuple.Create(" content=\"", 975), Tuple.Create("\"", 1008)
            
            #line 26 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 985), Tuple.Create<System.Object, System.Int32>(Version.CurrentVersion
            
            #line default
            #line hidden
, 985), false)
);

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"website\"");

WriteLiteral(" content=\"http://www.zkea.net\"");

WriteLiteral("/>\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1083), Tuple.Create("\"", 1126)
            
            #line 29 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1090), Tuple.Create<System.Object, System.Int32>(Url.PathContent(Model.Page.Favicon)
            
            #line default
            #line hidden
, 1090), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1.0,user-scalable=no,maximum-scale=1.0" +
"\"");

WriteLiteral(" />\r\n");

            
            #line 31 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 31 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (Model.Page.ExtendFields != null)
    {
        foreach (var meta in Model.Page.ExtendFields.Where(m => m.Title.IsNotNullAndWhiteSpace() && m.Title.StartsWith("meta_")))
        {

            
            #line default
            #line hidden
WriteLiteral("            <meta");

WriteAttribute("name", Tuple.Create(" name=\"", 1493), Tuple.Create("\"", 1531)
            
            #line 35 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1500), Tuple.Create<System.Object, System.Int32>(meta.Title.Replace("meta_","")
            
            #line default
            #line hidden
, 1500), false)
);

WriteAttribute("content", Tuple.Create(" content=\"", 1532), Tuple.Create("\"", 1553)
            
            #line 35 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1542), Tuple.Create<System.Object, System.Int32>(meta.Value
            
            #line default
            #line hidden
, 1542), false)
);

WriteLiteral(" />\r\n");

            
            #line 36 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 38 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
Write(StyleAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
Write(ScriptAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 40 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (Model.CurrentTheme != null)
    {
        if (HttpContext.Current.IsDebuggingEnabled)
        {

            
            #line default
            #line hidden
WriteLiteral("            <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1777), Tuple.Create("\"", 1828)
            
            #line 44 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1784), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.CurrentTheme.UrlDebugger)
            
            #line default
            #line hidden
, 1784), false)
);

WriteLiteral(" />\r\n");

            
            #line 45 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <link");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1920), Tuple.Create("\"", 1963)
            
            #line 48 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1927), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.CurrentTheme.Url)
            
            #line default
            #line hidden
, 1927), false)
);

WriteLiteral(" />\r\n");

            
            #line 49 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</head>\r\n<body");

WriteLiteral(" class=\"front\"");

WriteLiteral(">\r\n");

            
            #line 53 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (Request.IsAuthenticated)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"preview-toolbar\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-primary sort-handle\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"glyphicon glyphicon-move\"");

WriteLiteral("></i>\r\n                </a>\r\n");

            
            #line 60 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 60 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                 if (!Model.Page.IsPublishedPage)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2393), Tuple.Create("\"", 2470)
            
            #line 62 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2400), Tuple.Create<System.Object, System.Int32>(Url.Action("Design", "Page", new { module = "admin", Model.Page.ID })
            
            #line default
            #line hidden
, 2400), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-wrench\"");

WriteLiteral("></i>\r\n                        设计\r\n                    </a>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2642), Tuple.Create("\"", 2727)
            
            #line 66 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2649), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Page", new { module = "admin", PageID = Model.Page.ID })
            
            #line default
            #line hidden
, 2649), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-th\"");

WriteLiteral("></i>\r\n                        概览\r\n                    </a>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2895), Tuple.Create("\"", 2970)
            
            #line 70 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2902), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "Page", new { module = "admin", Model.Page.ID })
            
            #line default
            #line hidden
, 2902), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-edit\"");

WriteLiteral("></i>\r\n                        属性\r\n                    </a>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3140), Tuple.Create("\"", 3248)
            
            #line 74 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3147), Tuple.Create<System.Object, System.Int32>(Url.Action("PublishPage", "Page", new {module = "admin", Model.Page.ID, ReturnUrl = Model.Page.Url})
            
            #line default
            #line hidden
, 3147), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-open\"");

WriteLiteral("></i>\r\n                        发布\r\n                    </a>\r\n");

            
            #line 78 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                    if (Model.CurrentTheme != null && Model.CurrentTheme.IsPreView)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3530), Tuple.Create("\"", 3600)
            
            #line 80 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3537), Tuple.Create<System.Object, System.Int32>(Url.Action("CancelPreView", "Theme", new { module = "admin" })
            
            #line default
            #line hidden
, 3537), false)
);

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"glyphicon glyphicon-transfer\"");

WriteLiteral("></i>\r\n                            退出\r\n");

WriteLiteral("                            ");

            
            #line 83 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                       Write(Model.CurrentTheme.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            主题\r\n                        </a>\r\n");

            
            #line 86 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                    }
                    
            
            #line default
            #line hidden
            
            #line 87 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("Partial.Menu", Model));

            
            #line default
            #line hidden
            
            #line 87 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                                                        
                }
                else if (Model.PreViewPage != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4045), Tuple.Create("\"", 4127)
            
            #line 91 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4052), Tuple.Create<System.Object, System.Int32>(Url.Action("Design", "Page", new {module = "admin", Model.PreViewPage.ID})
            
            #line default
            #line hidden
, 4052), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral("></i>\r\n                        编辑\r\n                    </a>\r\n");

WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4299), Tuple.Create("\"", 4358)
            
            #line 95 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4306), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Page", new {module = "admin"})
            
            #line default
            #line hidden
, 4306), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-eye-open\"");

WriteLiteral("></i>\r\n                        页面\r\n                    </a>\r\n");

            
            #line 99 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                    if (Model.CurrentTheme != null && Model.CurrentTheme.IsPreView)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 4644), Tuple.Create("\"", 4714)
            
            #line 101 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4651), Tuple.Create<System.Object, System.Int32>(Url.Action("CancelPreView", "Theme", new { module = "admin" })
            
            #line default
            #line hidden
, 4651), false)
);

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"glyphicon glyphicon-transfer\"");

WriteLiteral("></i>\r\n                            退出\r\n");

WriteLiteral("                            ");

            
            #line 104 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                       Write(Model.CurrentTheme.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            主题\r\n                        </a>\r\n");

            
            #line 107 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5010), Tuple.Create("\"", 5103)
            
            #line 108 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5017), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Account", new { module = "admin", returnurl = Model.Page.Url })
            
            #line default
            #line hidden
, 5017), false)
);

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"glyphicon glyphicon-off\"");

WriteLiteral("></i>\r\n                        退出\r\n                    </a>\r\n");

            
            #line 112 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

            
            #line 115 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
        using (Script.AtFoot())
        {

            
            #line default
            #line hidden
WriteLiteral("            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                var toolBar = $(\".preview-toolbar\");\r\n                $(\".sort" +
"-handle\", toolBar).DragElement(toolBar);\r\n            </script>\r\n");

            
            #line 121 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 125 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 128 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
Write(StyleAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 129 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
Write(ScriptAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 130 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 130 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (!Model.Style.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 5682), Tuple.Create("\"", 5714)
            
            #line 132 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5689), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Style)
            
            #line default
            #line hidden
, 5689), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 133 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 134 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (!Model.Page.Style.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteAttribute("href", Tuple.Create(" href=\"", 5809), Tuple.Create("\"", 5846)
            
            #line 136 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5816), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Page.Style)
            
            #line default
            #line hidden
, 5816), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

            
            #line 137 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 138 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (!Model.Script.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5962), Tuple.Create("\"", 5994)
            
            #line 140 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 5968), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Script)
            
            #line default
            #line hidden
, 5968), false)
);

WriteLiteral("></script>\r\n");

            
            #line 141 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 142 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
     if (!Model.Page.Script.IsNullOrEmpty())
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 6105), Tuple.Create("\"", 6142)
            
            #line 144 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 6111), Tuple.Create<System.Object, System.Int32>(Url.Content(Model.Page.Script)
            
            #line default
            #line hidden
, 6111), false)
);

WriteLiteral("></script>\r\n");

            
            #line 145 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n\r\n</html>\r\n");

            
            #line 149 "..\..\Modules\Common\Views\Shared\_Layout.cshtml"
   
    ExecutePageFinish();

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
