#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Shared/_LayoutNormal.cshtml")]
    public partial class _Modules_Common_Views_Shared__LayoutNormal_cshtml : Easy.Web.Page.ViewPage<dynamic>
    {
        public _Modules_Common_Views_Shared__LayoutNormal_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
   
    Style.Reqiured("bootStrap").AtHead();

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<!--[if lt IE 7 ]><html");

WriteLiteral(" class=\"ie ie6\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 7 ]><html");

WriteLiteral(" class=\"ie ie7\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if IE 8 ]><html");

WriteLiteral(" class=\"ie ie8\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral("> <![endif]-->\r\n<!--[if (gte IE 9)|!(IE)]><!-->\r\n<html");

WriteLiteral(" class=\"not-ie\"");

WriteLiteral(" lang=\"zh\"");

WriteLiteral(">\r\n<!--<![endif]-->\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge,chrome=1\"");

WriteLiteral(">\r\n    <title>");

            
            #line 15 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 563), Tuple.Create("\"", 583)
, Tuple.Create(Tuple.Create("", 570), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 570), false)
);

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width,initial-scale=1.0,user-scalable=no,maximum-scale=1.0" +
"\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
Write(StyleAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
Write(ScriptAtHead());

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"container\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 23 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 25 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
Write(StyleAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Modules\Common\Views\Shared\_LayoutNormal.cshtml"
Write(ScriptAtFoot());

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
