#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Easy.Constant;
    using Easy.Extend;
    using Easy.Web.CMS;
    using Easy.Web.Extend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Modules/Common/Views/Shared/Partial.Menu.cshtml")]
    public partial class _Modules_Common_Views_Shared_Partial_Menu_cshtml : Easy.Web.Page.ViewPage<Easy.Web.CMS.Layout.LayoutEntity>
    {
        public _Modules_Common_Views_Shared_Partial_Menu_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
  
    string url = "~/";
    if (Model.Page != null)
    {
        url = Model.Page.Url;
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n    <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle Dropdown</span>\r\n</button>\r\n<ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 420), Tuple.Create("\"", 486)
            
            #line 16 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 427), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Dashboard", new { module = "admin" })
            
            #line default
            #line hidden
, 427), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-dashboard\"");

WriteLiteral("></i>\r\n            仪表盘\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 611), Tuple.Create("\"", 674)
            
            #line 22 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 618), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Layout", new { module = "admin" })
            
            #line default
            #line hidden
, 618), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-th-list\"");

WriteLiteral("></i>\r\n            布局列表\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 798), Tuple.Create("\"", 859)
            
            #line 28 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 805), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Page", new { module = "admin" })
            
            #line default
            #line hidden
, 805), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-eye-open\"");

WriteLiteral("></i>\r\n            页面管理\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 984), Tuple.Create("\"", 1051)
            
            #line 34 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 991), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Navigation", new { module = "admin" })
            
            #line default
            #line hidden
, 991), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-retweet\"");

WriteLiteral("></i>\r\n            导航管理\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1175), Tuple.Create("\"", 1237)
            
            #line 40 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 1182), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Theme", new { module = "admin" })
            
            #line default
            #line hidden
, 1182), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-blackboard\"");

WriteLiteral("></i>\r\n            主题管理\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1364), Tuple.Create("\"", 1426)
            
            #line 46 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 1371), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Media", new { module = "admin" })
            
            #line default
            #line hidden
, 1371), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon glyphicon-picture\"");

WriteLiteral("></i>\r\n            媒体库\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1559), Tuple.Create("\"", 1624)
            
            #line 52 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 1566), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Carousel", new { module = "admin" })
            
            #line default
            #line hidden
, 1566), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-hd-video\"");

WriteLiteral("></i>\r\n            焦点图\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1748), Tuple.Create("\"", 1812)
            
            #line 58 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 1755), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Article", new { module = "admin" })
            
            #line default
            #line hidden
, 1755), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-font\"");

WriteLiteral("></i>\r\n            文章列表\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1933), Tuple.Create("\"", 1997)
            
            #line 64 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 1940), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Product", new { module = "admin" })
            
            #line default
            #line hidden
, 1940), false)
);

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-list-alt\"");

WriteLiteral("></i>\r\n            产品列表\r\n        </a>\r\n    </li>\r\n    <li>\r\n        <a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"http://www.zkea.net/zkeacms/templates\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-save-file\"");

WriteLiteral("></i>\r\n            下载模板\r\n        </a>\r\n    </li>\r\n    <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n    <li>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2356), Tuple.Create("\"", 2438)
            
            #line 77 "..\..\Modules\Common\Views\Shared\Partial.Menu.cshtml"
, Tuple.Create(Tuple.Create("", 2363), Tuple.Create<System.Object, System.Int32>(Url.Action("Logout", "Account", new { module = "admin", returnurl = url })
            
            #line default
            #line hidden
, 2363), false)
);

WriteLiteral(" target=\"_self\"");

WriteLiteral(" title=\"退出登录\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"glyphicon glyphicon-off\"");

WriteLiteral("></i>\r\n            退出登录\r\n        </a>\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
